name: Build DualSense EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --onefile --icon=icon.ico dualsense_swipe.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: DualSense-EXE
          path: dist/dualsense_swipe.exe
